apiVersion: v1
kind: Service
metadata:
  name: pracuj-scrapper
spec:
  type: LoadBalancer
  selector:
    app1: job-offers-pracuj
  ports:
    - port: 80
      targetPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: pracuj-subscriber
spec:
  type: LoadBalancer
  selector:
    app2: job-offers-pracuj-subscriber
  ports:
    - port: 80
      targetPort: 5001


