apiVersion: v1
kind: Service
metadata:
  name: praca-scrapper
spec:
  type: LoadBalancer
  selector:
    app1: job-offers-praca
  ports:
    - port: 80
      targetPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: praca-subscriber
spec:
  type: LoadBalancer
  selector:
    app2: job-offers-praca-subscriber
  ports:
    - port: 80
      targetPort: 5001