apiVersion: apps/v1
kind: Deployment
metadata:
  name: praca-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app1: job-offers-praca
      app2: job-offers-praca-subscriber
  template:
    metadata:
      labels:
        app1: job-offers-praca
        app2: job-offers-praca-subscriber
    spec:
      containers:
        - name: app1
          image: gcr.io/scrapper-system/praca-offers-scrapper:v2
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
        - name: app2
          image: gcr.io/scrapper-system/praca-offers-db-handler:v2
          ports:
            - containerPort: 5001
          env:
            - name: PORT
              value: "5001"
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.28.0
          command:
            - "/cloud_sql_proxy"
            - "-ip_address_types=PRIVATE"
            - "-log_debug_stdout"
            - "-instances=scrapper-system:europe-central2:job-offers-pracuj-db=tcp:5432"
            - "-credential_file=/secrets/service_account.json"
          securityContext:
            runAsNonRoot: true
          volumeMounts:
            - name: sql-instance-secret-volume
              mountPath: /secrets/
              readOnly: true
          resources:
            requests:
              memory: "2Gi"
              cpu: "0.25"
      volumes:
        - name: sql-instance-secret-volume
          secret:
            secretName: sql-instance-secret