stages:
  - build-dev
  - deploy-dev
  - build-prod
  - deploy-prod

.only-dev:
  only:
    - dev

.only-prod:
  only:
    - prod

build-dev:
  stage: build-dev
  extends: .only-dev
  rules:
    - changes:
      - microservices/job_offers_scrapper/praca/*
  tags:
    - gitlab-runner
  image: "gcr.io/cloud-builders/gcloud"
  script:
    - cd microservices/job_offers_scrapper/praca
    - gcloud builds submit --tag "gcr.io/scrapper-system/praca-offers-scrapper-dev:$CI_COMMIT_SHORT_SHA"

