stages:
  - build-dev
  - deploy-dev
  - build-prod
  - deploy-prod

.only-dev:
  only:
    - dev

.only-prod:
  only:
    - prod

build-dev:
  stage: build-dev
  extends: .only-dev
  tags:
    - gitlab-runner
  image: "gcr.io/cloud-builders/gcloud"
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."
    - gcloud config get project