stages:
  - build-dev
  - deploy-dev
  - build-prod
  - deploy-prod

build-dev:
  stage: build-dev
  only:
    refs:
      - dev
    changes:
      #- microservices/job_offers_scrapper/praca/*
      - .gitlab-ci.yml
  tags:
    - gitlab-runner
  image: "gcr.io/cloud-builders/gcloud"
  script:
    - echo $STORAGE_SA > credentials-storage-scrapper.json
    - gcloud auth activate-service-account --key-file credentials-storage-scrapper.json
    - cd microservices/job_offers_scrapper/praca
    - gcloud config get account
    #- gcloud builds submit --tag "gcr.io/scrapper-system/praca-offers-scrapper-dev:$CI_COMMIT_SHORT_SHA"

