stages:
  - build-dev
  - build-prod
  - deploy-dev
  - deploy-prod

image: "gcr.io/cloud-builders/gcloud"

.build-dev:
  only:
    refs:
      - dev
    changes:
      - microservices/job_offers_scrapper/**/*

.build-prod:
  only:
    refs:
      - prod
    changes:
      - microservices/job_offers_scrapper/**/*

build-praca-scrapper-dev:
  stage: build-dev
  extends: .build-dev
  tags:
    - gitlab-runner
  script:
    - cd microservices/job_offers_scrapper/praca
    - gcloud builds submit --tag "gcr.io/scrapper-system/praca-offers-scrapper-dev:$CI_COMMIT_SHORT_SHA"

build-praca-subscriber-dev:
  stage: build-dev
  extends: .build-dev
  tags:
    - gitlab-runner
  script:
    - cd microservices/job_offers_scrapper/praca_subscriber
    - gcloud builds submit --tag "gcr.io/scrapper-system/praca-offers-db-handler-dev:$CI_COMMIT_SHORT_SHA"

build-pracuj-scrapper-dev:
  stage: build-dev
  extends: .build-dev
  tags:
    - gitlab-runner
  script:
    - cd microservices/job_offers_scrapper/pracuj
    - gcloud builds submit --tag "gcr.io/scrapper-system/pracuj-offers-scrapper-dev:$CI_COMMIT_SHORT_SHA"

build-pracuj-subscriber-dev:
  stage: build-dev
  extends: .build-dev
  tags:
    - gitlab-runner
  script:
    - cd microservices/job_offers_scrapper/pracuj_subscriber
    - gcloud builds submit --tag "gcr.io/scrapper-system/pracuj-offers-db-handler-dev:$CI_COMMIT_SHORT_SHA"

build-praca-scrapper-prod:
  stage: build-prod
  extends: .build-prod
  tags:
    - gitlab-runner
  script:
    - cd microservices/job_offers_scrapper/praca
    - gcloud builds submit --tag "gcr.io/scrapper-system/praca-offers-scrapper-prod:$CI_COMMIT_SHORT_SHA"

build-praca-subscriber-prod:
  stage: build-prod
  extends: .build-prod
  tags:
    - gitlab-runner
  script:
    - cd microservices/job_offers_scrapper/praca_subscriber
    - gcloud builds submit --tag "gcr.io/scrapper-system/praca-offers-db-handler-prod:$CI_COMMIT_SHORT_SHA"

build-pracuj-scrapper-prod:
  stage: build-prod
  extends: .build-prod
  tags:
    - gitlab-runner
  script:
    - cd microservices/job_offers_scrapper/pracuj
    - gcloud builds submit --tag "gcr.io/scrapper-system/pracuj-offers-scrapper-prod:$CI_COMMIT_SHORT_SHA"

build-pracuj-subscriber-prod:
  stage: build-prod
  extends: .build-prod
  tags:
    - gitlab-runner
  script:
    - cd microservices/job_offers_scrapper/pracuj_subscriber
    - gcloud builds submit --tag "gcr.io/scrapper-system/pracuj-offers-db-handler-prod:$CI_COMMIT_SHORT_SHA"

deploy-helm-chart-praca-dev:
  stage: deploy-dev
  only:
    refs:
      - dev
    changes:
      - microservices/job_offers_scrapper/praca/*
      - microservices/job_offers_scrapper/praca_subscriber/*
      - scrapper-system-chart-praca/**/*
  tags:
    - gitlab-runner-dev
  image: "dtzar/helm-kubectl"
  script:
    - sed -i "/^\\([[:space:]]*tag:\\).*/s//\\1$CI_COMMIT_SHORT_SHA/" scrapper-system-chart-praca/values.dev.yaml
    - helm upgrade scrapper-system-praca-dev scrapper-system-chart-praca/ --create-namespace -n dev -f scrapper-system-chart-praca/values.dev.yaml --atomic --install     

deploy-helm-chart-pracuj-dev:
  stage: deploy-dev
  only:
    refs:
      - dev
    changes:
      - microservices/job_offers_scrapper/pracuj/*
      - microservices/job_offers_scrapper/pracuj_subscriber/*
      - scrapper-system-chart-pracuj/**/*
  tags:
    - gitlab-runner-dev
  image: "dtzar/helm-kubectl"
  script:
    - sed -i "/^\\([[:space:]]*tag:\\).*/s//\\1$CI_COMMIT_SHORT_SHA/" scrapper-system-chart-pracuj/values.dev.yaml
    - helm upgrade scrapper-system-pracuj-dev scrapper-system-chart-pracuj/ --create-namespace -n dev -f scrapper-system-chart-pracuj/values.dev.yaml --atomic --install  

deploy-helm-chart-praca-prod:
  stage: deploy-prod
  only:
    refs:
      - prod
    changes:
      - microservices/job_offers_scrapper/praca/*
      - microservices/job_offers_scrapper/praca_subscriber/*
      - scrapper-system-chart-praca/**/*
  tags:
    - gitlab-runner-prod
  image: "dtzar/helm-kubectl"
  script:
    - sed -i "/^\\([[:space:]]*tag:\\).*/s//\\1$CI_COMMIT_SHORT_SHA/" scrapper-system-chart-praca/values.prod.yaml
    - helm upgrade scrapper-system-praca-prod scrapper-system-chart-praca/ --create-namespace -n prod -f scrapper-system-chart-praca/values.prod.yaml --atomic --install     

deploy-helm-chart-pracuj-prod:
  stage: deploy-prod
  only:
    refs:
      - prod
    changes:
      - microservices/job_offers_scrapper/pracuj/*
      - microservices/job_offers_scrapper/pracuj_subscriber/*
      - scrapper-system-chart-pracuj/**/*
  tags:
    - gitlab-runner-prod
  image: "dtzar/helm-kubectl"
  script:
    - sed -i "/^\\([[:space:]]*tag:\\).*/s//\\1$CI_COMMIT_SHORT_SHA/" scrapper-system-chart-pracuj/values.prod.yaml
    - helm upgrade scrapper-system-pracuj-prod scrapper-system-chart-pracuj/ --create-namespace -n prod -f scrapper-system-chart-pracuj/values.prod.yaml --atomic --install    
      