stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  tags:
    - gitlab-runner
  image: "gcr.io/cloud-builders/gcloud"
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."
    - gcloud config get project
    