stages:
  - build-dev
  - deploy-dev
  - build-prod
  - deploy-prod

.only-dev:
  only:
    refs:
      - dev

.only-prod:
  only:
    refs:
      - prod

build-dev:
  stage: build-dev
  only:
    refs:
      - dev
    changes:
      #- microservices/job_offers_scrapper/praca/*
      - .gitlab-ci.yml
  tags:
    - gitlab-runner
  image: "gcr.io/cloud-builders/gcloud"
  script:
    - cd microservices/job_offers_scrapper/praca
    - gcloud builds submit --tag "gcr.io/scrapper-system/praca-offers-scrapper-dev:$CI_COMMIT_SHORT_SHA"

