apiVersion: v1
kind: Pod
metadata:
  namespace: dev
spec:
  serviceAccountName: jenkins
  containers:
    - name: gcloud
      image: gcr.io/cloud-builders/gcloud
      command: ['cat']
      tty: true
    - name: helm
      image: dtzar/helm-kubectl
      command: [ 'cat' ]
      tty: true