apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.pracaScrapper.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.pracaScrapper.type }}
  selector:
    app1: {{ .Values.apps.praca.app1.name }}
  ports:
    - port: {{ .Values.service.pracaScrapper.port }}
      targetPort: {{ .Values.service.pracaScrapper.targetPort }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.pracaSubscriber.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.pracaSubscriber.type }}
  selector:
    app2: {{ .Values.apps.praca.app2.name }}
  ports:
    - port: {{ .Values.service.pracaSubscriber.port }}
      targetPort: {{ .Values.service.pracaSubscriber.targetPort }}