apiVersion: apps/v1
kind: Deployment
metadata:
  name: pracuj-deployment
  namespace: {{ .Values.namespace }}
spec:
  {{ if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{ end }}
  selector:
    matchLabels:
      app1: {{ .Values.apps.pracuj.app1.name }}
      app2: {{ .Values.apps.pracuj.app2.name }}
  template:
    metadata:
      labels:
        app1: {{ .Values.apps.pracuj.app1.name }}
        app2: {{ .Values.apps.pracuj.app2.name }}
    spec:
      containers:
        - name: {{ .Values.image.pracujScrapper.name }}
          image: {{ .Values.image.pracujScrapper.image }}:{{ .Values.image.pracujScrapper.tag }}
          ports:
            - containerPort: {{ .Values.image.pracujScrapper.containerPort }}
          env:
            - name: PORT
              value: {{ quote .Values.image.pracujScrapper.containerPort }}
          volumeMounts:
            - name: credentials-storage-scrapper
              mountPath: /secrets/
              readOnly: true
        - name: {{ .Values.image.pracujSubscriber.name }}
          image: {{ .Values.image.pracujSubscriber.image }}:{{ .Values.image.pracujSubscriber.tag }}
          ports:
            - containerPort: {{ .Values.image.pracujSubscriber.containerPort }}
          env:
            - name: PORT
              value: {{ quote .Values.image.pracujSubscriber.containerPort }}
          volumeMounts:
            - name: credentials-storage-scrapper
              mountPath: /secrets/
              readOnly: true
        - name: {{ .Values.image.cloudSqlProxy.name }}
          image: {{ .Values.image.cloudSqlProxy.image }}:{{ .Values.image.cloudSqlProxy.tagCloud }}
          command:
            {{- range .Values.image.cloudSqlProxy.command }}
            - {{ . | quote }}
            {{- end }}
          securityContext:
            runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
          volumeMounts:
            - name: {{ .Values.volumes.sqlVolume.name }}
              mountPath: /secrets/
              readOnly: true
          resources:
            requests:
              memory: "0.5Gi"
              cpu: "0.15"
      volumes:
        - name: {{ .Values.volumes.sqlVolume.name }}
          secret:
            secretName: {{ .Values.volumes.sqlVolume.secretName }}
        - name: credentials-storage-scrapper
          secret:
            secretName: credentials-storage-scrapper