apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.pracujScrapper.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.pracujScrapper.type }}
  selector:
    app1: {{ .Values.apps.pracuj.app1.name }}
  ports:
    - port: {{ .Values.service.pracujScrapper.port }}
      targetPort: {{ .Values.service.pracujScrapper.targetPort }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.pracujSubscriber.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.pracujSubscriber.type }}
  selector:
    app2: {{ .Values.apps.pracuj.app2.name }}
  ports:
    - port: {{ .Values.service.pracujSubscriber.port }}
      targetPort: {{ .Values.service.pracujSubscriber.targetPort }}


