apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-job-olx
spec:
  schedule: "0 21 * * 0"
  concurrencyPolicy: Allow
  startingDeadlineSeconds: 100
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-job-olx
            image: busybox
            args:
            - /bin/sh
            - -c
            - curl -X GET http://34.116.193.9
          restartPolicy: Never