apiVersion: apps/v1
kind: Deployment
metadata:
  name: praca-scrapper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-offers-praca
  template:
    metadata:
      labels:
        app: job-offers-praca
    spec:
      containers:
        - name: app
          image: gcr.io/scrapper-system/praca-offers-scrapper:v2
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"